USE sakila;

-- List the number of films per category.
SELECT category_id, COUNT(film_id) 
FROM sakila.film_category
GROUP BY category_id;

-- Retrieve the store ID, city, and country for each store.
SELECT store_id , city, country
FROM sakila.store AS s
JOIN sakila.address AS a
ON s.address_id = a.address_id
JOIN sakila.city AS c
ON a.city_id = c.city_id
JOIN sakila.country AS co
ON c.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT staff_id, SUM(amount) 
FROM sakila.payment
GROUP BY staff_id;

-- Determine the average running time of films for each category
SELECT category_id, AVG(length) AS "Duración media"
FROM sakila.film_category AS categoria
JOIN sakila.film AS peli 
ON peli.film_id = categoria.film_id
GROUP BY category_id;
